INSERT INTO ASESOR (NOMBRE,ESPECIALIDAD) VALUES ('ARMANDO CARLOS PALMERA','COMERCIAL');
INSERT INTO ASESOR (NOMBRE,ESPECIALIDAD) VALUES ('MAITIEL MORA','CAJERA');
INSERT INTO ASESOR (NOMBRE,ESPECIALIDAD) VALUES ('FELIX PALMERA','CAJERO');

INSERT INTO CLIENTE (NOMBRE,DIRECCION,CIUDAD,TELEFONO) VALUES ('CRUZ SÁNCHEZ','CALLE 72 # 68 - 59 BLOQ 15','BARRANQUILLA','3135301667');
INSERT INTO CLIENTE (NOMBRE,DIRECCION,CIUDAD,TELEFONO) VALUES ('JORGE PALMERA','CALLE 72 # 68 - 59 BLOQ 15','BARRANQUILLA','3135122567');


INSERT INTO TARJETA (NUMTARJETA,CCV,TIPTARJETA,ID_CLIENTE) VALUES (123456780923,234,'DEBITO',1);
INSERT INTO TARJETA (NUMTARJETA,CCV,TIPTARJETA,ID_CLIENTE) VALUES (0002309496,124,'CREDITO',2);


INSERT INTO DETALLE_CONSUMO(ID_TARJETA,DESCRIPCION,MONTO) VALUES(1,'COMPRA EURO',25000);
